application:
  name: sileht.net
  project: blog
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  custom_domains:
  - branch: master
    domain: qovery4.sileht.net
  routes:
  - application_name: sileht.net
    paths:
    - /*
